//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winform_3d_visualizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("winform_3d_visualizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pixel:hover
        ///{ 
        ///  stroke: #000;
        ///  stroke-width: 1px;
        ///}
        ///.tick:hover
        ///{ 
        ///  fill: #aaa;
        ////* stroke: #000;  
        ///stroke-width: 1px;*/
        ///}
        ///div.tooltip
        ///{
        ///	position: absolute;
        ///	text-align: left;
        ///	padding: 8px;
        ///	font: 12px sans-serif;
        ///	background: #000;
        ///  color: #ddd;
        ///	border: solid 1px #aaa;
        ///	border-radius: 4px;
        ///	pointer-events: none;
        ///}.
        /// </summary>
        internal static string correxplorer_css {
            get {
                return ResourceManager.GetString("correxplorer_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var stringify = function (x) {
        ///  if (typeof(x) === &apos;number&apos; || x === undefined) {
        ///    return String(x);
        ///    // otherwise it won&apos;t work for:
        ///    // NaN, Infinity, undefined
        ///  } else {
        ///    return JSON.stringify(x);
        ///  }
        ///};
        ///
        ///var main = function(corr, label_col, label_row){
        ///
        ///  var transition_time = 1500;
        ///
        ///  var body = d3.select(&apos;body&apos;);
        ///
        ///  var tooltip = body.select(&apos;div.tooltip&apos;);
        /////    .style(&quot;opacity&quot;, 1e-6);
        ///
        ///  var svg = body.append(&apos;svg&apos;)
        ///    .attr(&apos;width&apos;, 3000)
        ///    .attr(&apos;height&apos;, 3000);
        ///
        ///  // Autodetect s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string correxplorer_js {
            get {
                return ResourceManager.GetString("correxplorer_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(){function n(n){return n&amp;&amp;(n.ownerDocument||n.document||n).documentElement}function t(n){return n&amp;&amp;(n.ownerDocument&amp;&amp;n.ownerDocument.defaultView||n.document&amp;&amp;n||n.defaultView)}function e(n,t){return t&gt;n?-1:n&gt;t?1:n&gt;=t?0:NaN}function r(n){return null===n?NaN:+n}function i(n){return!isNaN(n)}function u(n){return{left:function(t,e,r,i){for(arguments.length&lt;3&amp;&amp;(r=0),arguments.length&lt;4&amp;&amp;(i=t.length);i&gt;r;){var u=r+i&gt;&gt;&gt;1;n(t[u],e)&lt;0?r=u+1:i=u}return r},right:function(t,e,r,i){for(arguments.length&lt;3&amp;&amp;(r=0) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d3_v3_min_js {
            get {
                return ResourceManager.GetString("d3_v3_min_js", resourceCulture);
            }
        }
    }
}
